### ISSUE TITLE
Relevamiento JF 20141107 con nuevos pedidos 20150108

### ISSUE THREAD

**Issue by nmonja** [githubmg/JFServicios#1]
Hola Fran, ¿todo ok? Te paso lo que te comenté de JF, algunas correcciones que habría que hacer, y tres funcionalidades nuevas para presupuestar. Por supuesto cualquier consulta avisame, beso y nos vemos mañana.

MODIFICACIONES Y CORRECCIONES:
- Agregar campo “Observaciones” (texto libre) a los movimientos de stock.
- Valores cedidos: Los cheques se repiten en varios casos; en alguno sólo el número de cheque con datos diferentes (cheque 49600434) y en otros casos con exactamente el mismo registro (cheque 49600441). Por un lado, habría que ver puntualmente qué pasó con esos cheques y solucionarlo desde la base de datos; por otro, cuando se quiere ingresar un cheque con un número y de un banco que ya existe, el sistema no debería permitirlo.
- Grillas de pedidos y compras: que por defecto salgan los pedidos y las compras ordenados por ID, de mayor a menor (las de mayor ID arriba de todo).
- Generar un reporte de ventas (pedidos), por fecha, que muestre un total de lo filtrado.
- Listados de cheques cedidos y cheques en cartera: que en ambos casos se muestre en algún lado el total de los cheques filtrados (o de todos, si no hay filtro aplicado).
- En el listado de cheques cedidos, los filtros de fechas “Desde” y “Hasta” deberían aplicarse a las fechas de vencimiento en lugar de a las fechas de emisión.
- El listado “Deudores por venta” suma IVA aún cuando se trate de pedidos no controlados.
- Corregir los cobros en el listado de deudores por venta y los pagos en el listado de acreedores por compra, dado que no impactaron las últimas modificaciones en la base de datos (VER PRIMERO NICO Y DODÓ, DESPUÉS EVENTUALMENTE CON FRAN).
- Los cheques ingresados por movimientos de caja, no se reflejan en el Listado de Valores en Cartera.
- En la carga de clientes, que siga siendo obligatorio completar el campo de correo electrónico, pero que tenga formato de texto libre.

NUEVAS FUNCIONALIDADES:

DEVOLUCIONES:
- En las compras, puede ocurrir que se devuelva al proveedor lo comprado, o parte de lo comprado. - En tal caso, el sistema debe contemplar el registro de dichas devoluciones.
- Debe poder relacionarse una devolución con la compra respectiva.
- Las devoluciones pueden ser totales o parciales.
- Cuando se hace una devolución, la mercadería devuelta debe restarse del stock.
- Además, debe ingresarse manualmente el importe correspondiente a dicha devolución.
- Debe haber, además, un campo optativo, “Número de Nota de Crédito”.

GESTIÓN DE CAJAS:
- El cliente requiere poder administrar más de una Caja (para los diferentes locales por ejemplo). En tal caso, haría falta lo siguiente:
  - Seleccionar caja cuando se registran cobros
  - Seleccionar caja cuando se registran pagos
  - Seleccionar caja cuando se realizan movimientos de caja
- Todo esto debe ser visualizado en un reporte, filtrando por caja (o viendo todas) y por supuesto por fecha. Debe visualizarse siempre con totales.
- Mostrar alerta de productos con stock negativo, menos para los productos de las familias “Servicios” y “Colocación y provisión”; idealmente, que pueda seleccionarse cuáles familias visualizar en el listado de stock (CHARLAR BIEN NICO Y FRAN).

**Comment by githubmg** [comment]
Nico, te comento lo que pasó con los cheques desde la estructura de datos: Los mismos se relacionan con un pago pero un mismo pago puede estar saldando varios pedidos.

Si bien todos los pedidos son del mismo cliente, la única manera de obtener el nombre de este cliente es pasando por la compra, porque el pago no está directamente asociado a un cliente. No me parece exactamente un error de diseño así que yo lo dejaría así. El problema en el reporte se arregla sencillamente haciendo un "SELECT DISTINCT"

**Comment by githubmg** [comment]
Comentario: Apliqué los filtros de fecha de AMBOS reportes de cheques a la fecha de vencimiento DEL cheque. Anteriormente lo teníamos relacionado a la fecha del cobro o del pedido respectivamente.

**Comment by nmonja** [comment]
Sos simplemente brillante Francesca.
Lic. Nicolás Monja
15-6577-7390 - nmonja@sysmo.com.ar (mailto:nmonja@sysmo.com.ar)
    Sysmo ConsultoraSantiago del Estero 454 - 8° 33www.sysmo.com.ar
(http://www.sysmo.com.ar/) (http://www.facebook.com/sysmoconsultora) 
(http://www.linkedin.com/company/sysmo) 
(http://plus.google.com/u/0/b/114990497392421970899/114990497392421970899/posts)
---- Original Message ----

**Comment by nmonja** [comment]
PARA VER EL LUNES, SIN APURO NI GRAN PRIORIDAD:

Reporte Deudores por venta:

Con la modificación del Reporte de pedidos, se agregaron varios clientes con el IVA como saldo pendiente (no deberían estar). Son:
- Carlos Arias
- Gamiz Stella Maris
- JL Consultores
- Karina Oliver
- Mariano Moreau
- Más adelante ver tema cómo impactan los estados en stock (ver en detalle Nico con Fran, validar con Facundo y presupuestar)

**Comment by nmonja** [comment]
AGREGADO VÍA TELEFÓNICA, 12/01/2015:

Reporte Deudores por venta: cuando cobrás una venta, te lo toma siempre sin IVA, entonces el IVA queda como deuda. Lo chequeé en Producción y es así, corregir de ser posible el miércoles 14/01 para actualizar en Test y Producción.
