### ISSUE TITLE
Errores 20141201

### ISSUE THREAD

**Issue by githubmg** [githubmg/JFServicios#2]
1) Valores cedidos se repiten: p.ej 49600434 y 49600441

2) Generar un reporte de pedidos filtrable por fecha que muestre el total. 

3) El listado de deudores por venta suma IVA aún cuando se trata de pedidos no controlados.

**Comment by githubmg** [comment]
Hola Nico

  El reporte de deudores era un desastre! Lo estoy rehaciendo bastante, para que informe el total por deudor. Aclaro la forma de cálculo: el precio_unitario es con el IVA incluído.
El reporte tendría:
                <th class="head0">CUIT</th>
                <th class="head0">Razón Social</th>
                <th class="head0">Total Facturado A Cliente</th>
                <th class="head0">Total Cobrado A Cliente</th>
                <th class="head0">Total Pendiente</th>     

Con filtro de fechas para los pedidos a considerar.

**Comment by nmonja** [comment]
¡Hola Fran! Que bueno que te diste cuenta pequeña... Un tema: el IVA debe
ir incluido si el pedido era controlado, en los no controlados obviamente
no se incluye el IVA.
Cualquier cosa avisame, beso,
Lic. Nicolás Monja
15-6577-7390 - nmonja@sysmo.com.ar (mailto:nmonja@sysmo.com.ar)
    Sysmo ConsultoraSantiago del Estero 454 - 8° 33www.sysmo.com.ar
(http://www.sysmo.com.ar/) (http://www.facebook.com/sysmoconsultora) 
(http://www.linkedin.com/company/sysmo) 
(http://plus.google.com/u/0/b/114990497392421970899/114990497392421970899/posts)
---- Original Message ----

**Comment by githubmg** [comment]
Por eso te decía el tema de cómo se calcula. La deuda de un pedido SIEMPRE sería:

 precio unitario \* cantidad - saldado  

porque el precio unitario ya incluye el IVA

**Comment by githubmg** [comment]
Y cuando es no controlado, según el descuento que se le haga al cliente o no, se pondrá un precio unitario más bajo, pero no es que si el producto cuesta 121 y el pedido es no controlado tengo que cobrarle 100. Así es como lo habíamos hablado con Dodó y es consistente con lo que hay en la base de JF

**Comment by nmonja** [comment]
Eso es Francesca... eso es...
Lic. Nicolás Monja
15-6577-7390 - nmonja@sysmo.com.ar (mailto:nmonja@sysmo.com.ar)
    Sysmo ConsultoraSantiago del Estero 454 - 8° 33www.sysmo.com.ar
(http://www.sysmo.com.ar/) (http://www.facebook.com/sysmoconsultora) 
(http://www.linkedin.com/company/sysmo) 
(http://plus.google.com/u/0/b/114990497392421970899/114990497392421970899/posts)
---- Original Message ----

**Comment by nmonja** [comment]
Tal cual Fran, es así como decís.
Saludos,
Lic. Nicolás Monja
15-6577-7390 - nmonja@sysmo.com.ar (mailto:nmonja@sysmo.com.ar)
    Sysmo ConsultoraSantiago del Estero 454 - 8° 33www.sysmo.com.ar
(http://www.sysmo.com.ar/) (http://www.facebook.com/sysmoconsultora) 
(http://www.linkedin.com/company/sysmo) 
(http://plus.google.com/u/0/b/114990497392421970899/114990497392421970899/posts)
---- Original Message ----
