### ISSUE TITLE
JF Modificaciones 032015

### ISSUE THREAD

**Issue by githubmg** [githubmg/JFServicios#5]
RELEVAMIENTO SISTEMA 25/02/2015

CORRECCIONES, AJUSTES Y NUEVAS FUNCIONALIDADES SOLICITADAS:

VALORES CEDIDOS SÓLO SUMA TOTAL Y NO PARCIALES AL FILTRAR POR COBRADOS O NO COBRADOS, O BIEN AL FILTRAR POR FECHA  (ok)

LOS CHEQUES DE EGRESO EN MOVIMIENTOS DE CAJA VAN A VALORES EN CARTERA Y NO A VALORES CEDIDOS; DEBEN IR A VALORES CEDIDOS. (ok)

VER TEMA DE STOCK AL SER PEDIDO PENDIENTE/TERMINADO/ANULADO (EJ: MERCADOLIBRE) / NICO: LOS PEDIDOS PENDIENTES Y ANULADOS NO DEBEN TOCAR STOCK; EN EL RESTO DE LOS ESTADOS, SÍ. (ok)

SI SE ANULA UN PEDIDO, NO DEBE FIGURAR EL SALDO PENDIENTE EN EL REPORTE DE DEUDORES POR VENTA (ok)

ARMAR UNA IMPRESIÓN TIPO FACTURA PARA LOS PEDIDOS NO CONTROLADOS, QUE SEA “PRESUPUESTO”. QUE SEA NUMERADO CORRELATIVO (DE 1 EN ADELANTE). QUE TENGA EL NOMBRE DEL CLIENTE, CHASIS, Y QUE DIGA CERTIFICADO DE GARANTÍA / PRIORIDAD ALTA.
(ok)

CLIENTES: CONSUMIDOR FINAL QUE SEA EL VALOR POR DEFECTO EN EL CAMPO “CONDICIÓN IVA”. (ok)

CUANDO SE HACE UNA FACTURA DE UN PEDIDO CONTROLADO PARA UN CLIENTE DE TIPO “B”, QUE NO GENERE REMITO.(El remito por la estructura de datos se vincula al pedido y a la factura, por lo tanto siempre tiene que existir para vincular una factura y un pedido. Lo que hice fue facturarlo automáticamente)

EN EL MÓDULO DE AGENDA: QUE EL CAMPO CLIENTE SEA DE TEXTO LIBRE, QUE NO TRAIGA EL CLIENTE CARGADO. (ok)

CAMBIAR NOMBRE “STOCK IRIGOYEN” POR “STOCK LOPE DE VEGA” EN TODOS LOS LUGARES DONDE ASÍ FIGURE (SE MUDARON, POR ESO PIDEN EL CAMBIO) (ok)

PODER CARGAR UN COBRO POR NUMERO DE FACTURA! / NICO: EN COBROS, BUSCA PEDIDOS POR EL NÚMERO DE PEDIDO, ESTO NO SIRVE, DEBE PODER PERMITIR BUSCAR POR EL NÚMERO DE FACTURA Y REMITO. (Actualmente es parte del criterio de búsqueda del  autocompletar)

PODER CARGAR EN LOS COBROS PERCEPCIONES Y COBROS PARCIALES (EJ: COBROS GALANTE) / NICO: LO QUE SE REQUIERE ES QUE EN LOS COBROS, SE PUEDA CARGAR UN CAMPO DE IMPORTE “RETENCIONES”, PROPIO DEL COBRO; ASIMISMO, ESTE IMPORTE DEBE IMPACTAR EN EL SALDO PENDIENTE DEL PEDIDO, JUSTAMENTE PARA QUE NO LE QUEDEN ESTOS PEDIDOS CON SALDOS PENDIENTES CUANDO EN REALIDAD SON RETENCIONES ABONADAS. Y EL MONTO CANCELADO DEBE SER = AL IMPORTE MÁS LAS RETENCIONES. (Sería lo mismo que hacer dos cobros para el mismo pedido ¿no?)

IVA COMPRA / NICO: HACER UN “REPORTE DE COMPRAS” QUE SEA EL ESPEJO DEL “REPORTE DE PEDIDOS” RECIENTEMENTE DESARROLLADO, CON TODOS LOS DATOS PERTINENTES EN LA PARTE SUPERIOR, TAL COMO FIGURAN EN EL REPORTE DE PEDIDOS ACTUALMENTE.(ok)

EN LA GRILLA DE PEDIDOS, QUE SE VEAN LAS OBSERVACIONES DEL PEDIDO. (ok)

EN LA GRILLA DE PEDIDOS, CUANDO SE PAGA UN PEDIDO CONTROLADO, RESTA COMO PENDIENTE EL IVA DE ESE PEDIDO (DADO QUE LOS PEDIDOS SE CARGAN SIN IVA, Y AL HACER LA FACTURA LO CALCULA SOLO). QUEDA ESE IMPORTE DE IVA COMO SALDO PENDIENTE, CUANDO NO DEBERÍA QUEDAR NADA. VER POR EJEMPLO PEDIDO NÚMERO 1255.(Ok )

ANULAR DECIMALES Y CANCELAR COMPRAS / PEDIDOS CON DEUDAS MENORES A $1. / NICO: HACER VARIAS COSAS:

SALDAR LAS COMPRAS Y PEDIDOS CON SALDO MENOR A $1

REVISAR LAS COLUMNAS DEL DEUDORES POR VENTA PARA QUE TENGA SÓLO DOS DECIMALES (QUE REDONDEE SI HACE FALTA). (OK)

CORREGIR LISTADO ACREEDORES POR COMPRAS (SÍMIL COMO FUNCIONA EL DE DEUDORES POR VENTA)

SE REPITEN CHEQUES EN VALORES EN CARTERA ! / NICO: YA LO HICIMOS PARA VALORES CEDIDOS; REPLICAR (VER CON FRAN) EN ESTE REPORTE. (OK si esto sólo pasaba en los casos en que un cheque entra por pedido y egresa por movimiento de caja.)

EN CUANTO AL IVA, EN MOVIMIENTOS DE CAJA, DE EGRESOS, DEBEN PODER CARGAR COSAS CONSIGNANDO NÚMERO DE FACTURA (CAMPO NUEVO) E IMPORTE DEL IVA (POR EJEMPLO, COMPRAN UNA TV Y QUIEREN TOMARSE EL IVA). EL IMPORTE DE ESE NUEVO CAMPO IVA DEBE TOMARSE PARA LA ESTADÍSTICA CORRESPONDIENTE DEL REPORTE DE COMPRAS (CHARLAR CON FRAN CÓMO HACER ESTO ÚLTIMO).

REPETICION DE VIN Y TRABAJOS / NICO: CUANDO PARA EL MISMO CHASIS SE CARGA UN ITEM QUE YA SE VENDIÓ, EL SISTEMA DEBE AVISAR QUE PARA ESE CHASIS YA SE HIZO EL PEDIDO xx EN FECHA XX/XX/XXXX (VER CON FRAN CÓMO CONVIENE DESARROLLARLO).
(OK)

VER TEMA PEDIDOS DE TALLER Y REPORTE PEDIDOS TALLER / NICO: CREAR PARA ESTO UN NUEVO DEPÓSITO “TALLER” Y UN NUEVO VENDEDOR “TALLER” Y UNA NUEVA DESCRIPCIÓN DE MOVIMIENTO DE CAJA “TALLER”.

MODIFICACIONES Y AGREGADOS (PRIORIDAD MÁS BAJA QUE TODO LO ANTERIOR):

DEVOLUCIONES / EMPEZADO (FRAN APROX. 7 HORAS):
En las compras, puede ocurrir que se devuelva al proveedor lo comprado, o parte de lo comprado. En tal caso, el sistema debe contemplar el registro de dichas devoluciones.
Debe poder relacionarse una devolución con la compra respectiva.
Las devoluciones pueden ser totales o parciales.
Cuando se hace una devolución, la mercadería devuelta debe restarse del stock.
Además, debe ingresarse manualmente el importe correspondiente a dicha devolución.
Debe haber, además, un campo optativo, “Número de Nota de Crédito”.

GESTIÓN DE CAJAS (FRAN 7 HORAS):
El cliente requiere poder administrar más de una Caja (para los diferentes locales por ejemplo). En tal caso, haría falta lo siguiente:
Seleccionar caja cuando se registran cobros
Seleccionar caja cuando se registran pagos
Seleccionar caja cuando se realizan movimientos de caja
Todo esto debe ser visualizado en un reporte, filtrando por caja (o viendo todas) y por supuesto por fecha. Debe visualizarse siempre con totales.

Mostrar alerta de productos con stock negativo, menos para los productos de las familias “Servicios” y “Colocación y provisión”; idealmente, que pueda seleccionarse cuáles familias visualizar en el listado de stock / FRAN 5 HORAS.

**Comment by nmonja** [comment]
Hola Fran. Agrego las observaciones que me traje de mi visita a JF el miércoles pasado. La semana que viene, si tenemos tiempo, deberíamos avanzar con esto y con el resto de las modificaciones que aún no hicimos. Nos vemos el miércoles, cualquier cosa estamos hablando, beso:
- En la base de Producción, cuando van a "Imprimir presupuesto", y hacen click en el link "ver presupuesto" de cualquiera que figure, les sale un error "Could not find stored procedure 'dbo.rptPresupuesto_detalle'." (¿habrá faltado cargar ese store en la base de Producción?) / OK
- En la impresión de los presupuestos (se las mostré en el ambiente de Test), debajo del logo, cambiar los datos porque se mudaron:
  Av. Lope de Vega 2041
  5263-0745
  1564404292
  info@jfservicios.com
  www.jfservicios.com
- Modificación de una cosa que hicimos: los pedidos en estado "Pendiente" sí tienen que tocar stock (los de estado "Anulado", no). / OK
- Nuevo reporte: "Movimientos de Productos". Filtro por producto, y por fecha desde y fecha hasta. Ordenados descentemente por fecha (arriba de todo los más recientes) deben mostrarse las compras, ventas y movimientos de stock del producto seleccionado, mostrando qué tipo de movimiento es (compra, venta, movimiento de ingreso de stock o movimiento de egreso), la fecha del movimiento, y la razón social del que compró o vendió (si se trata de una compra o una venta). / OK
